    import './Card.css';
    import Line from './line';
    const First = () =>{
        
        return(
        <div className='card'>  
            
            <Line text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer viverra, velit sed rhoncus viverra, libero metus vulputate tortor, vel pharetra elit nibh ut mi. Etiam sollicitudin vestibulum massa non varius. Suspendisse bibendum pulvinar elit, vitae auctor orci tincidunt vitae. Mauris ullamcorper semper iaculis. Nulla facilisi. Curabitur rhoncus dui sed tincidunt pretium. Integer leo lectus, maximus ac vulputate in, euismod non risus. In hac habitasse platea dictumst. Praesent faucibus ultricies fermentum. Aliquam rutrum posuere nulla sollicitudin tincidunt. Proin rutrum, tellus vel mattis hendrerit, tellus nunc rhoncus metus, vitae elementum erat lorem non metus. Sed id pellentesque orci. Nam erat erat, blandit."/>
            <Line text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer viverra, velit sed rhoncus viverra, libero metus vulputate tortor, vel pharetra elit nibh ut mi. Etiam sollicitudin vestibulum massa non varius. Suspendisse bibendum pulvinar elit, vitae auctor orci tincidunt vitae. Mauris ullamcorper semper iaculis. Nulla facilisi. Curabitur rhoncus dui sed tincidunt pretium. Integer leo lectus, maximus ac vulputate in, euismod non risus. In hac habitasse platea dictumst. Praesent faucibus ultricies fermentum. Aliquam rutrum posuere nulla sollicitudin tincidunt. Proin rutrum, tellus vel mattis hendrerit, tellus nunc rhoncus metus, vitae elementum erat lorem non metus. Sed id pellentesque orci. Nam erat erat, blandit."/>
            <Line text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer viverra, velit sed rhoncus viverra, libero metus vulputate tortor, vel pharetra elit nibh ut mi. Etiam sollicitudin vestibulum massa non varius. Suspendisse bibendum pulvinar elit, vitae auctor orci tincidunt vitae. Mauris ullamcorper semper iaculis. Nulla facilisi. Curabitur rhoncus dui sed tincidunt pretium. Integer leo lectus, maximus ac vulputate in, euismod non risus. In hac habitasse platea dictumst. Praesent faucibus ultricies fermentum. Aliquam rutrum posuere nulla sollicitudin tincidunt. Proin rutrum, tellus vel mattis hendrerit, tellus nunc rhoncus metus, vitae elementum erat lorem non metus. Sed id pellentesque orci. Nam erat erat, blandit."/>
            <Line text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer viverra, velit sed rhoncus viverra, libero metus vulputate tortor, vel pharetra elit nibh ut mi. Etiam sollicitudin vestibulum massa non varius. Suspendisse bibendum pulvinar elit, vitae auctor orci tincidunt vitae. Mauris ullamcorper semper iaculis. Nulla facilisi. Curabitur rhoncus dui sed tincidunt pretium. Integer leo lectus, maximus ac vulputate in, euismod non risus. In hac habitasse platea dictumst. Praesent faucibus ultricies fermentum. Aliquam rutrum posuere nulla sollicitudin tincidunt. Proin rutrum, tellus vel mattis hendrerit, tellus nunc rhoncus metus, vitae elementum erat lorem non metus. Sed id pellentesque orci. Nam erat erat, blandit."/>
            <Line text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer viverra, velit sed rhoncus viverra, libero metus vulputate tortor, vel pharetra elit nibh ut mi. Etiam sollicitudin vestibulum massa non varius. Suspendisse bibendum pulvinar elit, vitae auctor orci tincidunt vitae. Mauris ullamcorper semper iaculis. Nulla facilisi. Curabitur rhoncus dui sed tincidunt pretium. Integer leo lectus, maximus ac vulputate in, euismod non risus. In hac habitasse platea dictumst. Praesent faucibus ultricies fermentum. Aliquam rutrum posuere nulla sollicitudin tincidunt. Proin rutrum, tellus vel mattis hendrerit, tellus nunc rhoncus metus, vitae elementum erat lorem non metus. Sed id pellentesque orci. Nam erat erat, blandit."/>
            </div>
        )
    }
    export default First;
